Removed All Possible Bloats
gitpod-io/dockerfreeze pull request #68
Opened 2020-03-26 15:19 UTC by Uniminin

In rhis commit I've tried to remove all bloats as much as possible. Also I've rearranged pretty much everything in a good order. Overall code is more standard and high quality than before.

2020-03-26 15:19 UTC, Uniminin commented
@JesterOrNot @Kreyren Ping!!!

2020-03-26 15:31 UTC, Kreyren commented
@Uniminin Did you make any benchmarks for this?

2020-03-26 15:34 UTC, Kreyren commented
lgtm excluding results from benches

2020-03-26 18:02 UTC, JesterOrNot requested changes
Thank you! :tada:
Just a few suggestions

2020-03-26 18:02 UTC, JesterOrNot commented on gui/gui.py
> +    mainWindow = sg.Window('Docker Freeze Gui', default_element_size=(40, 1)).Layout(layout)
2 things,
1. Dockerfreeze is all one word
2. GUI is all caps

2020-03-27 06:40 UTC, Uniminin commented
@JesterOrNot There you go. You're most welcome.

2020-03-27 21:59 UTC, JesterOrNot commented
LGTM

2020-03-27 21:59 UTC, merged